### ISSUE TITLE
JSONDecoderError: AZURE_SUBSCRIPTION_ID = az('account list --query "[?isDefault][id]" --all -o tsv')

### ISSUE THREAD

**Issue by scheung38** [MarkWarneke/Az.Cli#14]
**Describe the bug**
AZURE_SUBSCRIPTION_ID = az('account list --query "[?isDefault][id]" --all -o tsv') does not seem to work inside Python

**To Reproduce**

**Expected behavior**
In setenv.sh:
```
#!/bin/sh
AZURE_SUBSCRIPTION_ID=$(az account list --query "[?isDefault][id]" --all -o tsv)
echo ${AZURE_SUBSCRIPTION_ID}

4d9XXXX-XXXX-XXXXXX-XXXXXXXXXXXX

```

But inside test.py:

`    AZURE_SUBSCRIPTION_ID = az('account list --query "[?isDefault][id]" --all -o tsv')
`
Exception has occurred: JSONDecodeError
Extra data: line 1 column 2 (char 1)

**Desktop (please complete the following information):**
 - OS: Mac OSX 
 - Browser chrome, 
 

**Additional context**
So how do we capture the stdout to screen as az commands output to screen only and it is not returned as results to be tested? i.e
 
account list --query "[?isDefault][id]" --all -o tsv

az account list -o table

ad sp create-for-rbac --name servicePrincipalArthurPAF > aks4seb1app
 {
   "appId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
   "displayName": "servicePrincipalID,
   "password": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "tenant": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
 }

**Comment by edtroleis** [comment]
Hello!

To query some results using the library az.cli you use different approach. Example:

# az cli command
az ad user show --id email@domain.com --query id -o tsv

Using the library
result = az("ad user show --id email@domain.com)[1]['id']"

There is an article to help you with more examples: https://markwarneke.me/2021-03-14-Query-Azure-Resources-Using-Python/

Regards.

**Comment by MarkWarneke** [comment]
Thanks @edtroleis this is the correct way to do it.

It's important to realize that the query has `-o tsv` as an argument.
This forces the cli to output tab-separated values instead of JSON.

Internally the script is using a `json.loads` to parse the output of the underlying library. 
So `JSONDecodeError` is expected if no JSON is found as an output.

https://github.com/MarkWarneke/Az.Cli/blob/c69eed85afb81bcb34e49b87ef81608f18fc137c/src/az/cli.py#L117

This is also an issue if you configure the azure cli to print `tsv` by default. See [CLI configuration file](https://learn.microsoft.com/en-us/cli/azure/azure-cli-configuration#cli-configuration-file)
